# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7a1d66f3e0be065e99a5496c333eeb85"
application_url = "https://excluded-bench-fighters-gary.trycloudflare.com"
embedded = true
name = "boa-home-task-DV"
handle = "boa-home-task-dv"

[build]
include_config_on_deploy = true
dev_store_url = "home-assignment-110.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://excluded-bench-fighters-gary.trycloudflare.com/auth/callback",
  "https://excluded-bench-fighters-gary.trycloudflare.com/auth/shopify/callback",
  "https://excluded-bench-fighters-gary.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
